openapi: 3.0.0
info:
  version: 0.1.0
  title: Empty Spec
servers:
  - url: 'http://localhost:8080/'
    description: Localhost
security:
  - bearer: []
tags:
  - name: Common Endpoints
    description: A collection of common endpoints
paths:
  /:
    get:
      tags:
        - Common Endpoints
      summary: Return basic service information
      responses:
        200:
          description: Default response
          content:
            "application/hal+json":
              schema:
                type: "object"
                properties:
                  name:
                    type: "string"
                  version:
                    type: "string"
